### ISSUE TITLE
issue on september month

### ISSUE THREAD

**Issue by sandy1000** [sebastianknopf/jQuery-Calendar#1]
please check, issue on september month of 2019,  should start from sunday  but its on monday can you please fix it

![image](https://user-images.githubusercontent.com/8776233/61146196-2a991c00-a4f9-11e9-9473-012c61c6ec3c.png)

**Comment by subham-stha** [comment]
> please check, issue on september month of 2019, should start from sunday but its on monday can you please fix it
> 
> ![image](https://user-images.githubusercontent.com/8776233/61146196-2a991c00-a4f9-11e9-9473-012c61c6ec3c.png)

i think its a problem for each month which starts from sunday, so may be it has issue with the function that creates calendar. if you can fix ASAP then it would be very helpful for me as well.

**Comment by skoegl** [comment]
You should have a fix now ;)

**Comment by sebastianknopf** [comment]
Thank you very much! I will commit your PR ASAP! :-)
