### ISSUE TITLE
jquery calendar don't understand 2020 year and month if page refresh

### ISSUE THREAD

**Issue by MrWebDevNusrat** [sebastianknopf/jQuery-Calendar#3]

**Comment by Brett-Henning** [comment]
Hi,

I had this issue too. When in the month of January the system fails. Found the issue...

The current month is 0 which is interpreted as false in the query.

The code below solves the problem

if(month === 0){
			currentMonth = month;
		}else{
			currentMonth = month || ((next) ? ((tmp[0] === options.months[options.months.length - 1]) ? 0 : options.months.indexOf(tmp[0]) + 1) : ((tmp[0] === options.months[0]) ? 11 : options.months.indexOf(tmp[0]) - 1));
		}

**Comment by Brett-Henning** [comment]
ps. 
This is in file:  jquery.calendar.js
On line:  77

**Comment by sebastianknopf** [comment]
Thank you for reporting the issue! I'll test the code mentioned by Slaine-Skeleton and update the repo ASAP.

**Comment by sebastianknopf** [comment]
I've updated the mentioned lines - thank you for contributing and reporting the issue!
